# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/fawei/Downloads/z20/525743/FPGA/Zynq_musicPlayer_FPGA/Zynq_musicPlayer_FPGA.srcs/sources_1/bd/system/ip/system_axi_i2s_adi_0_0/system_axi_i2s_adi_0_0.xci
# IP: The module: 'system_axi_i2s_adi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fawei/Downloads/z20/525743/FPGA/Zynq_musicPlayer_FPGA/Zynq_musicPlayer_FPGA.gen/sources_1/bd/system/ip/system_axi_i2s_adi_0_0/axi_i2s_adi_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_i2s_adi_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/fawei/Downloads/z20/525743/FPGA/Zynq_musicPlayer_FPGA/Zynq_musicPlayer_FPGA.srcs/sources_1/bd/system/ip/system_axi_i2s_adi_0_0/system_axi_i2s_adi_0_0.xci
# IP: The module: 'system_axi_i2s_adi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fawei/Downloads/z20/525743/FPGA/Zynq_musicPlayer_FPGA/Zynq_musicPlayer_FPGA.gen/sources_1/bd/system/ip/system_axi_i2s_adi_0_0/axi_i2s_adi_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_i2s_adi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
